behaviors:
  Driver AI:
    trainer_type: ppo
    hyperparameters: 
      batch_size: 128
      buffer_size: 40960
      # buffer_size: 16384
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.3
      lambd: 0.9
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings: 
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: none #hyper
      deterministic: false
    reward_signals: 
      extrinsic: 
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 512
    summary_freq: 50000
